[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/admin/"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/checkout"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/checkout/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/free"
  to = "/free-plugins.html"
  status = 200

[[redirects]]
  from = "/free/"
  to = "/free-plugins.html"
  status = 200

[[redirects]]
  from = "/free-plugins"
  to = "/free-plugins.html"
  status = 200

[[redirects]]
  from = "/free-plugins/"
  to = "/free-plugins.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
